### PR TITLE
Include activations in Sequential example.

### PR DESCRIPTION
**Pull request by melissatan**
# Includes a non-linearity in the example code.

## Checklist
- [x] This PR fixes a minor issue (e.g.: typo or small bug) or improves the docs (you can dismiss the other
      checks if that's the case).
- [ ] This change is discussed in a Github issue/
      [discussion](https://github.com/google/flax/discussions) (please add a
      link).
- [ ] The documentation and docstrings adhere to the
      [documentation guidelines](https://github.com/google/flax/blob/main/docs/README.md#how-to-write-code-documentation).
- [ ] This change includes necessary high-coverage tests.
      (No quality testing = no merge!)

### CODE REVIEW

**Review by marcvanzee — APPROVED** [review]
LGTM but @avital also had some comments during the Flax sync yesterday about this docstring so I'll add him as a reviewer as well.

UPDATE: ah I see you added him already 😃

**Comment by melissatan** [comment]
@marcvanzee thanks for the heads up! Just read from the Flax sync notes that @avital had suggested getting rid of the loop in the docstring example. Have updated the PR to remove the for-loop.

**Review by avital — APPROVED** [review]
Thanks!

**Comment by melissatan** [comment]
Thanks for the review! Removing the pull-ready label temporarily because it looks like the doc is broken at this PR https://flax--1978.org.readthedocs.build/en/1978/flax.linen.html#combinators 
Will add back the label once this is sorted out.

**Comment by melissatan** [comment]
The doc looks fine now, after resolving the merge conflict.

**Pull request merged**
