### PR TITLE
Fix link to orbax documentation

### PR DESCRIPTION
**Pull request by cool-RR**
## Checklist
- [X] This PR fixes a minor issue (e.g.: typo or small bug) or improves the docs (you can dismiss the other
      checks if that's the case).

### CODE REVIEW

**Review by cgarciae — APPROVED** [review]
Thanks @cool-RR!

**Comment by cool-RR** [comment]
@cgarciae I believe the test failure is not related to my change.

**Comment by cgarciae** [comment]
@cool-RR the issue is with pre-commit, please run:

```bash
pip install pre-commit
pre-commit run --all-files
```

**Comment by cool-RR** [comment]
@cgarciae Sorry, done now.

**Comment by cool-RR** [comment]
@cgarciae Is this good for merging?

**Pull request merged**
