### PR TITLE
Fixing pattern in examples/nlp_seq due to lack of shuffling

### PR DESCRIPTION
**Pull request by gan3sh500**
As mentioned in this [issue](https://github.com/google/flax/issues/166) nlp__seq was missing shuffling in the tf dataset. I have added it and re ran the code with the same batch size and training iterations and reproduced a similar accuracy.

### CODE REVIEW

**Comment by AlexeyG** [comment]
@gan3sh500 Just to make sure - could you please sign the CLA? This is required for us to be able to accept your PR. Thank you!

**Comment by gan3sh500** [comment]
Sorry forgot about it. Signed now.

**Comment by avital** [comment]
Hi @gan3sh500 -- I'm so sorry for this laying unmerged for so long. In the meanwhile we moved to `linen_examples/` for all of our new examples. Do you want to want to submit a new PR (without changing the README) to `linen_examples/nlp_seq/`? Alternatively we could just apply your change and reference this old PR for acknowledgement.

(cc @bohnetbd @bastings as the owners of the nlp_seq example)

**Comment by bohnetbd** [comment]
Thanks for the suggestion. With this example, we do not go for high accuracy and to keep it simple. In addition and more important maybe, I see also that there was no accuracy gain from shuffling. So that I would hesitate to take this change in before we get clear picture that this would help for other languages. I would rather close this PR if fine with all.

**Comment by gan3sh500** [comment]
@avital @bohnetbd Shall I take it up. I need to go through the code. I've forgotten it kind of.

**Comment by avital** [comment]
Hi @bohnetbd -- I found this old improvement to nlp_seq while cleaning up my GitHub issues. Can you please review it?

**Comment by bohnetbd** [comment]
Hi @avital and @gan3sh500,

I would suggest to not take this up as the accuracy improvements are not give and we want to focus only a simple example here. In case, we would like to work on accuracy, we could use pertained embeddings or character embeddings which would lead to very high accuracy gains.

so lets close this. Thank you all!

**Pull request closed without merging**
