### PR TITLE
PPO Linen example

### PR DESCRIPTION
**Pull request by wrzadkow**
Reinforcement learning (proximal policy optimization) example ported to Linen API. See PR #470 for the original (i.e. non-Linen) example.

### CODE REVIEW

**Comment by avital** [comment]
What are the remaining issues on this example for it to be merged? /cc @wrzadkow @jheek

**Comment by wrzadkow** [comment]
@googlebot I signed it!

**Comment by wrzadkow** [comment]
Hi Avital, from my perspective there are no major issues to fix here but of course I'm open to suggestions from code review. In the meantime, I committed the same changes that were introduced for non-Linen example in PR #541 . Thanks for following up!

**Review by jheek — APPROVED** [review]
Thanks Wojciech! Sorry for the delay from my side.

**Pull request merged**
