### PR TITLE
improved Embed input type check

### PR DESCRIPTION
**Pull request by nestordemeure**
Previous check was not accepting some valid integer types such as int8.

### CODE REVIEW

**Review by jheek — APPROVED** [review]
Thanks! The `issubtype` looks nicer also

**Comment by levskaya** [comment]
@nestordemeure - would you want to add that to this PR as well?

**Comment by nestordemeure** [comment]
PR updated.

**Comment by levskaya** [comment]
@nestordemeure - thanks so much for that!

**Pull request merged**
