### PR TITLE
run pytype for linen examples

### PR DESCRIPTION
**Pull request by jheek**
Add pytype testing to linen examples

### CODE REVIEW

**Comment by avital** [comment]
This change LGTM but looks like tests are failing on this branch for some reason? (about FLAGS?)

Do we also want to run mypy?

**Comment by avital** [comment]
Assigning to you @jheek until the build passes. Feel free to reassign to me once the build passes and then we can merge it.

**Comment by jheek** [comment]
@avital Should be fixed now

**Comment by avital** [comment]
Thanks, I'll merge this.

**Pull request merged**
