### PR TITLE
typo

### PR DESCRIPTION
**Pull request by katelee168**
# What does this PR do?

Fixes # typo

## Checklist
- [ X] This PR fixes a minor issue (e.g.: typo or small bug) or improves the docs (you can dismiss the other
      checks if that's the case).
- [ ] This change is discussed in a Github issue/
      [discussion](https://github.com/google/flax/discussions) (please add a
      link).
- [ ] The documentation and docstrings adhere to the
      [documentation guidelines](https://github.com/google/flax/blob/master/docs/README.md#how-to-write-code-documentation).
- [ ] This change includes necessary high-coverage tests.
      (No quality testing = no merge!)

### CODE REVIEW

**Comment by avital** [comment]
Hi @katelee168 -- actually this file is deprecated and speaks of the pre-Linen API! I'll remove it and replace it with a link to https://github.com/google/flax/discussions and https://flax.readthedocs.io/en/latest/howtos.html

**Comment by avital** [comment]
faq.md has been deleted (https://github.com/google/flax/tree/master/docs), I think you forked this from an old revision?

**Comment by katelee168** [comment]
I probably ended up here from a Google search. Glad there's more up to date
docs!

**Comment by avital** [comment]
I fixed that: https://flax.readthedocs.io/en/linen-rtd/faq.html. Thanks for letting us know!

**Pull request closed without merging**
