### PR TITLE
Optimize repeated function calls in serialization.py

### PR DESCRIPTION
**Pull request by kshithijiyer**

### CODE REVIEW

**Comment by danielsuo** [comment]
Thanks for this! If I understand the PR correctly, is this refactoring two calls to `register_serializationg_state` into a `for` loop?

I think we'd prefer to keep the original for easier reading since it's just two lines and the change doesn't improve performance.

Please let me know if I'm mistaken!

**Comment by AlexeyG** [comment]
Ping @kshithijiyer

**Comment by kshithijiyer** [comment]
> Ping @kshithijiyer 

Pong @AlexeyG

**Comment by kshithijiyer** [comment]
> Thanks for this! If I understand the PR correctly, is this refactoring two calls to `register_serializationg_state` into a `for` loop?
> 
> I think we'd prefer to keep the original for easier reading since it's just two lines and the change doesn't improve performance.
> 
> Please let me know if I'm mistaken!

Feel free to close the PR if you prefer the original one.

**Comment by jheek** [comment]
I don't think the for loop makes the code more readable. I'll close this issue for now.

**Pull request closed without merging**
