### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by i-chaochen**
extra . causes requirements.txt installable.

# What does this PR do?

Fixes # (issue)

## Checklist
- [x] This PR fixes a minor issue (e.g.: typo or small bug) or improves the docs (you can dismiss the other
      checks if that's the case).
- [ ] This change is discussed in a Github issue/
      [discussion](https://github.com/google/flax/discussions) (please add a
      link).
- [ ] The documentation and docstrings adhere to the
      [documentation guidelines](https://github.com/google/flax/blob/main/docs/README.md#how-to-write-code-documentation).
- [ ] This change includes necessary high-coverage tests.
      (No quality testing = no merge!)

### CODE REVIEW

**Comment by cgarciae** [comment]
@i-chaochen this is annoying but its required for ReadTheDocs, see failed `docs/readthedocs.org:flax` build in github actions checks.

**Comment by cgarciae** [comment]
As a solution simply re-run `pip install -e .` after installing doc requirements.

**Comment by i-chaochen** [comment]
Sorry you can close it.

**Comment by cgarciae** [comment]
@i-chaochen this is annoying but its required by ReadTheDocs, see [build failure](https://readthedocs.org/projects/flax/builds/18340698) where you get:

```
ModuleNotFoundError: No module named 'flax'
```
As a simple solution simply re-run:
```bash
pip install -e .
```
after installing the doc requirements.

**Pull request closed without merging**
