### PR TITLE
feat(misc): create `pyproject.toml`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Reference: #2817, #2828

@cgarciae 

# What does this PR do?

This PR aims to minimize the number of configuration files for the project. Instead of a separate `.style.yapf`, `mypy.ini`, `pytest.ini`, `pytype.cfg` and `setup.cfg`, we now would have all the configurations within the `pyproject.toml` file leading to a overall minimal code structure. I've also updated the `.pre-commit-config.yaml` file with the addition of a "check-toml" hook.

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
Ahh, finally the tests passed 😄 .

Follow up comments and questions:

- Should we also move the `pylintrc` into the `pyproject.toml`. I understand flax being managed by a Google Team it might be preferred to keep the `pylintrc`.
- As mentioned by @cgarciae in [this comment](https://github.com/google/flax/pull/2828#issuecomment-1412613984), we can also get rid of the `setup.py` and move the packaging content and metadata into `pyproject.toml`

**Comment by cgarciae** [comment]
Awesome @SauravMaheshkar!

> Should we also move the pylintrc into the pyproject.toml. I understand flax being managed by a Google Team it might be preferred to keep the pylintrc.

As I understand Google uses a separate linter so there is no need to keep a separate `pylintrc` file.

> As mentioned by @cgarciae in https://github.com/google/flax/pull/2828#issuecomment-1412613984, we can also get rid of the setup.py and move the packaging content and metadata into pyproject.toml

You can try to do it here or in a separate PR after this one is merged, your choice :)

**Comment by SauravMaheshkar** [comment]
> Awesome @SauravMaheshkar!
> 
> > Should we also move the pylintrc into the pyproject.toml. I understand flax being managed by a Google Team it might be preferred to keep the pylintrc.
> 
> As I understand Google uses a separate linter so there is no need to keep a separate `pylintrc` file.
> 
> > As mentioned by @cgarciae in [#2828 (comment)](https://github.com/google/flax/pull/2828#issuecomment-1412613984), we can also get rid of the setup.py and move the packaging content and metadata into pyproject.toml
> 
> You can try to do it here or in a separate PR after this one is merged, your choice :)
> 
> Edit: we are going to discuss if we want to use a build system like `poetry` so maybe wait a bit on removing `setup.py`.

Alright, maybe we merge this first and then I'll tackle the `pylintrc` in another PR. and I'll hold on the `setup.py` as well.

**Review by cgarciae — APPROVED** [review]
Thanks @SauravMaheshkar for doing this!

**Comment by SauravMaheshkar** [comment]
This PR aims to merge config files into a single `pyproject.toml` file. Isn't the only merge conflict because of `pytest.ini` ? (which this PR aims to remove)

**Comment by cgarciae** [comment]
Hey @SauravMaheshkar , can you pull the latest updates from `main`, then merge or rebase from `main` into the branch for this PR, solve the conflicts, and then push again?

We like this initiative but cant continue because of merge conflicts.

**Comment by SauravMaheshkar** [comment]
@cgarciae now it should be okay, right ?

**Comment by SauravMaheshkar** [comment]
Oh, I've already signed the CLA, Please refer to the attached screenshort. I'm assuming because of the merge from main, the CLA check is failing.

Screenshot 2023-03-01 at 3 29 25 PM

**Comment by cgarciae** [comment]
Hey @SauravMaheshkar, I'd love to get this in.
You want to finish it or take it on from here?

**Pull request closed without merging**
