### PR TITLE
Delete flax.optim.rst

### PR DESCRIPTION
**Pull request by ppwwyyxx**
This module no longer exists

# What does this PR do?

Fixes # (issue)

## Checklist
- [x] This PR fixes a minor issue (e.g.: typo or small bug) or improves the docs (you can dismiss the other
      checks if that's the case).
- [ ] This change is discussed in a Github issue/
      [discussion](https://github.com/google/flax/discussions) (please add a
      link).
- [x] The documentation and docstrings adhere to the
      [documentation guidelines](https://github.com/google/flax/blob/main/docs/README.md#how-to-write-code-documentation).
- [ ] This change includes necessary high-coverage tests.
      (No quality testing = no merge!)

### CODE REVIEW

**Comment by cgarciae** [comment]
@andsteing can we delete this now?

**Comment by 8bitmp3** [comment]
cc @jheek @levskaya @IvyZX

**Review by levskaya — APPROVED** [review]
Thanks for catching this!

**Comment by levskaya** [comment]
@cgarciae - I see some doctest failures of the form `AttributeError: module 'jax.test_util' has no attribute 'check_eq'` <-- is this a new issue cropping up?

**Comment by cgarciae** [comment]
@levskaya never seen this. Is it happening on `main` too?

**Pull request merged**
