### PR TITLE
Update python version support

### PR DESCRIPTION
**Pull request by cgarciae**
# What does this PR do?

* Removes support for python 3.7
* Add support for python 3.10

### CODE REVIEW

**Comment by zaxtax** [comment]
Should 3.11 be included?

**Comment by cgarciae** [comment]
@zaxtax good question, not sure what are current policy is. Maybe @levskaya or @marcvanzee can give some insight into how we are deciding which versions to support?

**Comment by 8bitmp3** [comment]
Thanks @cgarciae !

**Comment by wookayin** [comment]
Of course python3.11 should be supported, and the only reason if we could miss py311 is due to tensorflow. Flax itself does work with python3.11 without TF installed (Note: TF doesn't support python 3.11 yet), but in tests there are some optional dependency. If we can add a route of testing that could skip everything that depends on TF, we can make py311 supported.

**Comment by levskaya** [comment]
@zaxtax @cgarciae - JAX / jaxlib supports 3.11.   TF isn't expecting to release 3.11 support until 2023Q1 (so a month or two).

The main issue is trying to test anything without TF support... there are a ton of tests that rely on tf.data.  If y'all wanted to add a bunch of skip_test annotations we might be able to test against it sooner.

**Review by levskaya — APPROVED** [review]

**Comment by wookayin** [comment]
I have been installing and using flax on python 3.11, and there's no significant problems so far (other than the tensorflow/tensorstore dependencies issues, like #2692). Flax itself should have no problems running on python 3.11 so py311 can be included if we workaround TF-related tests. I would like to take over it and send some PRs.

**Comment by wookayin** [comment]
@cgarciae @levskaya Shouldn't we have `python_requires >= 3.7` in https://github.com/google/flax/blob/main/setup.py? Otherwise, once flax breaks on python 3.7, `flax` releases installed on python3.7 via `pip install flax` will be broken.

**Comment by cgarciae** [comment]
Thought about this but while correct it seemed too harsh just in case someone is stuck in 3.7 and by chance we don't break it. I'll send a tentative PR with this change so we can discuss it.

**Pull request merged**
