### PR TITLE
fixed math expressions 

### PR DESCRIPTION
**Pull request by banda-larga**
equations rendered incorrectly in Guides

# What does this PR do?

fixes math expressions rendered incorrectly in jax for the impatient and flax basics

### CODE REVIEW

**Comment by cgarciae** [comment]
Hey @banda-larga, thanks for doing this! You are missing the `pre-commit` hooks to sync the markdown and jupyter notebooks  as detailed in the [How to Contribute](https://flax.readthedocs.io/en/latest/advanced_topics/contributing.html) guide. Please run:

```bash
pip install pre-commit
pre-commit install
pre-commit run --all-files
```

**Comment by banda-larga** [comment]
@cgarciae yes, sorry, done it!

**Comment by cgarciae** [comment]
Thanks @banda-larga! I was wondering if you could fix an additional one? After 

> The linear approximation of f at point $x$ reads:

in `jax_for_the_impatient.md` we are also missing a new line.

**Review by marcvanzee — APPROVED** [review]
Thank you!

**Pull request merged**
