### PR TITLE
Added checkpointing howto

### PR DESCRIPTION
**Pull request by rolandgvc**
This HOWTO showcases loading and saving models from checkpoints.

### CODE REVIEW

**Comment by rolandgvc** [comment]
Should this be more "interesting" as in the imagenet example?

**Comment by avital** [comment]
I think it's perfect that this is "uninteresting". Does this work though? I don't think you've imported `checkpoints`

**Comment by avital** [comment]
Awesome, look good! Can you add a link from docs/howtos.rst? You can find more details on how to test docs locally in docs/README.md

**Comment by rolandgvc** [comment]
After running `make html` and building the files in `_build/html` I don't see any changes in the `howtos.rst`. What should I be looking for?

**Comment by avital** [comment]
You should change howto.rst to point to your new howto

**Comment by avital** [comment]
Thanks!

**Pull request merged**
