### PR TITLE
add stochastic check

### PR DESCRIPTION
**Pull request by jheek**

### CODE REVIEW

**Comment by avital** [comment]
LGTM for the change but please add a commit message that explains what this change does.

**Comment by jheek** [comment]
amended  commit with description

**Comment by adarob** [comment]
This still lacks documentation, and I'm not sure what to do to make my test in #111 pass.

**Comment by adarob** [comment]
Does this mean that nn.stochastic doesn't pass through any functions or just jitted functions? It appears to be the former. Is that intentional?

**Comment by adarob** [comment]
Figured it out -- I didn't realize the `nn.stochastic` scope should also not cross the `lax.scan` boundaries, so this is WAI. However, I think we should still add documentation to `stochastic.py` to make this clear.

**Pull request merged**
