### PR TITLE
Migrating ConvLSTM from Flax to Linen

### PR DESCRIPTION
**Pull request by mbz**

### CODE REVIEW

**Comment by avital** [comment]
For context, here are the original PRs introducing `ConvLSTM` in current Flax: #422 #453

**Comment by mbz** [comment]
Ping

**Comment by avital** [comment]
@mohitreddy1996 do you think you'll have time to review this soon?

**Comment by mohitreddy1996** [comment]
Sorry for the delay and thanks for the change!

**Review by mohitreddy1996 — APPROVED** [review]

**Review by mohitreddy1996 — APPROVED** [review]

**Pull request merged**
