### PR TITLE
Add support for single example pooling

### PR DESCRIPTION
**Pull request by jheek**
recognizes batch free inputs in pooling layers see. Fixes https://github.com/google/flax/issues/739

### CODE REVIEW

**Review by levskaya — APPROVED** [review]
lgtm! thanks!

**Comment by levskaya** [comment]
(looks like an unrelated `Could not load dynamic library 'libcudart.so.11.0'` failure is breaking the tests)

**Comment by jheek** [comment]
I think that's a standard warning. The real issue seems to be a symbol mismatch "_ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb". I think the tensorflow and tensorflow-text versions are incompatible. Will investigate further

**Comment by avital** [comment]
Oh, I forgot to ask: Can you please add an item in the CHANGELOG? I think we decided that we'll try to do that on every PR.

**Pull request merged**
