### PR TITLE
Add link to DotGeneral in DenseGeneral doc.

### PR DESCRIPTION
**Pull request by lucasb-eyer**

### CODE REVIEW

**Comment by MostafaDehghani** [comment]
Isn't it better to link to the `lax.dot_general` in JAX instead of XLA?
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.dot_general.html

**Comment by lucasb-eyer** [comment]
I thought about that first, but the only useful thing in that documentation is the link to XLA's doc, so why two clicks when one can do? :)

**Comment by lucasb-eyer** [comment]
But I guess it doesn't hurt to have both links in case the `lax.dot_general` becomes more useful in the future, so added that too. (Sorry, 2 commits as I use github's UI for this PR)

**Comment by MostafaDehghani** [comment]
Thanks you @lucasb-eyer.

**Pull request merged**
