### PR TITLE
Replace flax named_call with upstream version jax.named_call

### PR DESCRIPTION
**Pull request by qiuminxu**
Since https://github.com/google/jax/pull/4796 has merged, we can replace flax named_call to jax.named_call so that https://github.com/google/jax/pull/4649 finds the correct primitive.

### CODE REVIEW

**Comment by andsteing** [comment]
Hi Qiumin

Thanks for the PR. Are the JAX changed already released? See our failing tests.

**Comment by qiuminxu** [comment]
> Hi Qiumin
> 
> Thanks for the PR. Are the JAX changed already released? See our failing tests.

Looks like it is not released yet, the PR just merged today.

**Review by jheek — CHANGES_REQUESTED** [review]
Thanks for the PR! Please make sure to raise the Jax version constraint to the appropriate version.

**Comment by qiuminxu** [comment]
> Thanks for the PR! Please make sure to raise the Jax version constraint to the appropriate version.

Thanks for the review. The PR now builds correctly with proper jax version.

**Comment by avital** [comment]
@qiuminxu I don't see an update to https://github.com/google/flax/blob/master/setup.py bumping the minimum JAX version

**Comment by qiuminxu** [comment]
> @qiuminxu I don't see an update to https://github.com/google/flax/blob/master/setup.py bumping the minimum JAX version

Right, bumped it to 0.2.6.

**Pull request merged**
