### PR TITLE
Fix to use `is_initializing` for init-detection.

### PR DESCRIPTION
**Pull request by yotarok**
# What does this PR do?

The logic used for detecting initialization-mode in `linen.BatchNorm` is currently based on mutability of `params`.
There's a clean approach to do it by `Module.is_initializing` and the previous logic does not work if the user provides `mutable=True`.

## Checklist
- [x] This PR fixes a minor issue (e.g.: typo or small bug) or improves the docs (you can dismiss the other
      checks if that's the case).
- [ ] This change is discussed in a Github issue/
      [discussion](https://github.com/google/flax/discussions) (please add a
      link).
  - (No GitHub issue posted yet)
- [x] The documentation and docstrings adhere to the
      [documentation guidelines](https://github.com/google/flax/blob/main/docs/README.md#how-to-write-code-documentation).
- [ ] This change includes necessary high-coverage tests.
      (No quality testing = no merge!)
  - Covered by the existing tests on `BatchNorm`

### CODE REVIEW

**Comment by cgarciae** [comment]
@levskaya was there a reason not to do the change proposed in this PR when you introduced `is_initializing`?

**Comment by cgarciae** [comment]
@yotarok can you merge/rebase with `main` to fix the tests?

**Comment by yotarok** [comment]
@cgarciae Thanks for the comment. Rebased and force-pushed.

**Comment by levskaya** [comment]
> @levskaya was there a reason not to do the change proposed in this PR when you introduced `is_initializing`?

Mostly I was overwhelmed and dropped it - Since it is a subtle change in semantics we need to test this against existing users to make sure we're not introducing a potentially invisible breaking change...  and probably announce the behavior change.

**Comment by yotarok** [comment]
I agree, once this PR is approved, we (or Flax core devs) should announce the behavior change.
FYI, the issue I described above in PR description is also invisible.  When a user provides `mutable=True` to `apply`, `BatchNorm` silently stops updating the statistics, and it's hard to notice because the return value still contains those non-updated BatchNorm stats, and there's no warning message.

**Comment by yotarok** [comment]
Ping.
Or, should I work on improving coverage for getting this reviewed?

**Comment by jheek** [comment]
@yotarok I'm going to run a large internal test suite to check if this breaks in surprising way.

**Review by jheek — APPROVED** [review]

**Pull request merged**
