### PR TITLE
Implement default dtype FLIP

### PR DESCRIPTION
**Pull request by jheek**

### CODE REVIEW

**Comment by marcvanzee** [comment]
> Any update here? I guess this is still stuck in internal tests?

It is really very close to being done. I reviewed the internal code, but @jheek is currently on vacation for one week. I expect that he will be able to get it in next week.

**Comment by PhilipVinc** [comment]
Thanks infinitely!

Can I assume the flax-side of things is done, and test this from within NetKet to see if raises any issues?

**Comment by marcvanzee** [comment]
> Thanks infinitely!
> 
> Can I assume the flax-side of things is done, and test this from within NetKet to see if raises any issues?

Yes I think so, @jheek still has to implement some changes but I don't think there were bugs in his code. Only some typing errors, so please ignore those if you are testing.

**Comment by PhilipVinc** [comment]
Thanks!

I tried replacing NetKet's Dense and Convoluted vendored layers (we were vendoring them to support complex numbers) with the ones defined in flax here and  the whole test suite completed without problems.

I also tried to run a bunch of my own experiments and it also worked correctly.

I'd like to really thank you for working on this and allowing us to remove our vendored copies.

**Comment by marcvanzee** [comment]
Great to hear! @jheek did amazing work, and the credit goes to him fully 😄 .

**Comment by PhilipVinc** [comment]
❤️

**Comment by jheek** [comment]
@PhilipVinc It has finally been merged :)

**Comment by PhilipVinc** [comment]
thanks for your undying commitment!

Do you plan to tag a new release of flax soon?

**Comment by jheek** [comment]
Yeah I can do that on Monday

**Comment by jheek** [comment]
> Do you plan to tag a new release of flax soon?

I have just pushed a release

**Pull request merged**
