### PR TITLE
Fixes `launch_gce.sh` with imagenet example.

### PR DESCRIPTION
**Pull request by andsteing**
This PR mainly updates the automated launch script `examples/cloud/launch_gce.sh` - while fixing this, the requirements for the `imagenet` example also required updating for new JAX versioning.

Updates script to work with newer containers. See [`examples/cloud/README.md`](https://github.com/google/flax/blob/main/examples/cloud/README.md) for more details.

Tested with:

```
# Update these for your project...
PROJECT=flax-xgcp
WORKDIR_BASE=gs://flax_eu/examples
TFDS_BASE=gs://tensorflow-datasets/datasets

# Run directly from this PR
REPO=https://github.com/andsteing/flax
BRANCH=examples

# Launch VM with 1x V100 in west1-a
python examples/cloud/launch_gce.py \
   --project=$PROJECT \
   --zone=us-west1-a \
   --machine_type=n1-standard-8 \
   --accelerator_type=nvidia-tesla-v100 \
   --accelerator_count=1 \
   --gcs_workdir_base=$WORKDIR_BASE \
   --tfds_data_dir=$TFDS_BASE \
   --repo=$REPO \
   --branch=$BRANCH \
   --example=imagenet \
   --args='--config=configs/default.py' \
   --name=imagenet_v100
```

Command for launching on 2 GPUs (note that this also allows us to scale CPUs from 8 to 16)

```
python examples/cloud/launch_gce.py \
   --project=$PROJECT \
   --zone=us-west1-a \
   --machine_type=n1-standard-16 \
   --accelerator_type=nvidia-tesla-v100 \
   --accelerator_count=2 \
   --gcs_workdir_base=$WORKDIR_BASE \
   --tfds_data_dir=$TFDS_BASE \
   --repo=$REPO \
   --branch=$BRANCH \
   --example=imagenet \
   --args='--config=configs/default.py' \
   --name=imagenet_v100
```

Note that you can add `--wait` or `--connect` to above commands to make the command wait until all is launched or connect into the VM once it's ready (and then detach from [tmux](https://github.com/tmux/tmux/wiki) via `CTRL-b d`.

When logged in, you'll see the ongoing training like this:

image

Above launcher will also output commands to follow the training using TensorBoard

image

And links to training artifacts and logs on GCS:

image

### CODE REVIEW

**Review by chiamp — APPROVED** [review]
LGTM

**Comment by marcvanzee** [comment]
This is great! @andsteing do you think it is useful to add this to the Google Cloud JAX documentation, perhaps [here](https://cloud.google.com/tpu/docs/run-calculation-jax#running_jax_code_on_a_tpu_vm)? Right now the script is a bit hidden away.

Or is this still experimental and not meant to be used broadly?

**Comment by andsteing** [comment]
Personally, I find this quite useful, but it's definitely on the experimental side.

I propose that others start using it for launching jobs on public cloud (that way we also make sure the image references etc stay up to date), and if they also find it useful, we could start advertising it a bit more.

I'd also love to compare this approach with #2619 to better understand if we can simply use existing commands, or if there is indeed value in having such a script.

**Comment by marcvanzee** [comment]
@cgarciae did you ever try running Andreas' script? I think you have access to a v3-8 right, maybe you could see how easy it is to run something from OS?

**Pull request merged**
