### PR TITLE
Flax docs restructuring: introduce Developer notes (ex-Advanced), move Contributing and Philosophy to main ToC, and other changes

### PR DESCRIPTION
**Pull request by 8bitmp3**
Partially addresses https://github.com/google/flax/issues/2627 by @marcvanzee 

1. Move 6 docs out of _Advanced Topics_:
- Move **CONTRIBUTING.md** to the main ToC --> Make the Contributing guide visible to (new) users/future contributors. 
- Move **The Flax philosophy** to the main ToC (@marcvanzee maybe we can move it to _Developer notes_ - see below) --> Make the Philosophy visible.
- Move **Dealing with Flax Module arguments** to _Guides_.
- Move **Convert PyTorch to Flax** to _Guides_.
- Move **Upgrading my codebase to Optax** to _Guides_.
- Move **Upgrading my codebase to Linen** to _Guides_.
2. Rename _Advanced Topics_ to _Developer notes_.
3. Move _The Sharp Bits_ to _Guides_.
4. Add the Scenic library to the _Ecosystem_ section on the landing page.
5. Update the landing page.
6. Minor updates to/linting of various docs, including:
- CONTRIBUTING.md
- The INDEX pages
- The Flax philosophy
- Convert PyTorch to Flax

### CODE REVIEW

**Comment by andsteing** [comment]
Thanks for starting this effort, Olzhas!

Some comments:

1. I think the `Flax - The Sharp Bits` is too prominent. Let's remove the emojis (btw I don't think we need to mention "Flax" in the title, either) and move it into another topic. Especially since currently this page is very short and doesn't actually address a lot of sharp bits yet (we might move it further up later on if it becomes a main component of the documentation).
2. Upgrading to Optax and Linen is not actually a developer note, but this is very much geared towards users of Flax, so let's move this out of "Developer notes".
3. "Guides" has become quite long by now; what about restructuring it into multiple sub-categories? By topic and/or advancedness.
4. What about making "Examples" expand similarly to Guides/Developer Notes/API Reference?

**Comment by 8bitmp3** [comment]
> ... `Flax - The Sharp Bits`... don't think we need to mention "Flax" in the title, either) and move it into another topic.

Good idea. Done. For now, it's in the _Developer notes_ as _The Sharp Bits_.

> Upgrading to Optax and Linen is not actually a developer note, but this is very much geared towards users of Flax, so let's move this out of "Developer notes".

Good idea. Moved to Guides.

> "Guides" has become quite long by now; what about restructuring it into multiple sub-categories? By topic and/or advancedness.

TODO: @8bitmp3 

> What about making "Examples" expand similarly to Guides/Developer Notes/API Reference?

TODO: @8bitmp3

**Comment by andsteing** [comment]
> > ... `Flax - The Sharp Bits`... don't think we need to mention "Flax" in the title, either) and move it into another topic.
> 
> Good idea. Done. For now, it's in the _Developer notes_ as _The Sharp Bits_.
> 

Thanks. Though, similar to "upgrading to Optax", I think that the "sharp bits" are pretty much geared towards users, and not Flax developers, so I would also move them into "Guides" (or rather a sub-category of "Guides" when we have that).

**Comment by 8bitmp3** [comment]
TODO: Migrate Linen design principles and Flax Philosophy. Add redirects. cc @marcvanzee

**Comment by 8bitmp3** [comment]
TODO: Add `google-research` open-sourced examples that use Flax cc @marcvanzee @andsteing @levskaya @IvyZX @cgarciae @chiamp @jheek (e.g. to a new section like "Research")

**Review by marcvanzee — APPROVED** [review]
Awesome change @8bitmp3, so many small fixes, really happy you are making all these improvements!

LGTM assuming you resolve the conflict.

**Pull request closed without merging**
