### PR TITLE
Convert all onp references to np

### PR DESCRIPTION
**Pull request by levskaya**
Just a version of @8bitmp3 #798 merged cleanly into master.

### CODE REVIEW

**Comment by levskaya** [comment]
@8bitmp3 I merged your PR into master, but I need you to give the googlebot CLA robot consent as detailed above before I can actually merge it.

**Review by levskaya — COMMENTED** [review]
Just noting that I've visually confirmed the only changes in this PR are onp->np import renames.

**Comment by 8bitmp3** [comment]
@googlebot I consent.

**Comment by 8bitmp3** [comment]
@levskaya Thank you, this is awesome

**Pull request merged**
