### PR TITLE
Document the `flax.optim` Adam optimizer

### PR DESCRIPTION
**Pull request by 8bitmp3**
Hi @avital I've begun to update the docstings for `flax.optim` optimizers (https://github.com/google/flax/issues/661 - "Need to add all optimizers to Read The Docs", [milestone](https://github.com/google/flax/milestone/9)). I'm using the Google style guide ([functions and methods](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) and [classes](https://google.github.io/styleguide/pyguide.html#384-classes)), although stuff like 4-space indentation may be not applicable here.

Main changes:
- Add a longer description of the optimizer
- Provide a reference to the original paper (useful stuff, users can check the default param values, pseudo-code, etc)
- Add attributes with default values
- Character limit at 80 per line (used a linter)

Next:
- Attributes are the same as arguments in the constructor (`__init__`) - should we only keep attributes then? Currently, args (from the constructor) don't seem to appear on the Sphinx "front-end" - https://flax.readthedocs.io/en/latest/flax.optim.html#optimizers 
- [UPDATE] Args from `__init__` [can be auto-documented](https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method). There's a PR from @BertrandRdp https://github.com/google/flax/pull/672/files that should help with that (it updates `conf` and `flax.optim.rst`).

```py
class Adam(OptimizerDef):
  """Adam optimizer.

  Implements Adam - a stochastic gradient descent method (SGD) that computes
  individual adaptive learning rates for different parameters from estimates of
  first- and second-order moments of the gradients. 
  
  Reference: [Adam: A Method
  for Stochastic Optimization](https://arxiv.org/abs/1412.6980v8) (Kingma and
  Ba, 2014).

  Attributes:
    learning_rate: The learning rate — the step size used to update the
      parameters.
    beta1: The exponentian decay rate for the 1st moment estimates. The
      coefficient used to calculate the first moments of the gradients (the
      moving average of the gradient) (default: 0.9).
    beta2: The exponentian decay rate for the 2nd moment estimates. The
      coefficient used to calculate the second moments of the gradients (the
      moving average of the gradient magnitude) (default: 0.999).
    eps: A small scalar added to the gradient magnitude estimate to improve
      numerical stability (default: 1e-8).
    weight_decay: The learning rate decay (default: 0.0).
  """
...
```

Thanks 👋

### CODE REVIEW

**Comment by avital** [comment]
Looks like @BertrandRdp is changing the optimizer docstrings in #672, including Adam, so let's wait for that to land and see if there are other changes here that we should include. Apologies for the poor coordination...

**Comment by 8bitmp3** [comment]
No worries @avital 👋

**Comment by marcvanzee** [comment]
Assigning this to @BertrandRdp and @8bitmp3 so they can figure out how to incorporate these changes after #672 is merged.

**Comment by BertrandRdp** [comment]
Hi there!

We merged #672 but reverted the change to the conf file and we're not showing both class and init documentation in the docs. So I think that we can merge your update including some of the init docs at the class level once you resolve conflicts. I'm not sure about keeping a duplicate in init and at the class level, maybe only one is enough?

**Comment by 8bitmp3** [comment]
> So I think that we can merge your update including some of the init docs at the class level once you resolve conflicts. I'm not sure about keeping a duplicate in init and at the class level, maybe only one is enough?

Thanks very much @BertrandRdp - having only one was the plan, while displaying two in the initial commit provided an option to remove one of them (I wasn't sure which one is used to display the docs.) 👍

**Review by levskaya — APPROVED** [review]

**Pull request merged**
