### PR TITLE
Adds HOWTO: TF functions in Flax

### LINKED ISSUE #899: What is the Flax equivalent of Tensorflow functions?
For reference, I'm listing some Tensorflow functions below for which users asked what the equivalent is in Flax.

| TF Function  | Flax/jax Function |
| ------------- | ------------- |
| `tf.identity`  | `lambda x: x`  |
| `tf.name_scope()`  |   "Create submodule" [1] |
| `tf.print`  |  [`host_callback.id_print`](https://jax.readthedocs.io/en/latest/jax.experimental.host_callback.html#jax.experimental.host_callback.id_print) |

[1] Putting anything inside a new Module would have that effect. You can also always give submodules a name explicitly with the `name=... kwarg` to the submodule constuctor.

### PR DESCRIPTION
**Pull request by marcvanzee**
Closes #899 

RTD preview: https://flax.readthedocs.io/en/tf-howto/howtos/tf_functions.html

### CODE REVIEW

**Comment by avital** [comment]
I don't think many researchers outside of Google use TF these days so this seems like a very low priority HOWTO to add, and in fact may confuse people reading our RTD page to think that there's any relationship between TF and JAX... My vote would be to not add this to our official docs, but maybe there are additional perspectives

**Comment by marcvanzee** [comment]
A few users asked these questions, and I thought it would be useful to have them documented somewhere. Ideally these would have been asked in a Github Discussion where a user asks "how do I do X in TF?", and someone replies. However, the conversation was held somewhere else.

I do agree with the fact that these look a bit odd and potentially confusing as HOWTOs. Perhaps we just ignore these cases and just answer them again on Github Discussions if someone ends up asking them again. WDYT?

**Comment by avital** [comment]
Another option is to simply file a discussion now with the content of this HOWTO and call it a day ("Just posting this here for future reference: some people asked about ...") -- at least that way we can point people to a discussion URL if they ask again.

**Comment by marcvanzee** [comment]
Closed by #916

**Pull request closed without merging**
