### PR TITLE
Selective optimization howto

### PR DESCRIPTION
**Pull request by rolandgvc**
HOWTO demonstrating how to only train selected parameters.

### CODE REVIEW

**Comment by avital** [comment]
I think something here is wrong? The diff contains many unrelated changes

**Comment by rolandgvc** [comment]
Yes, I rebased off origin/master. For some reason I have the same issues with #279, but not with #227. Am I doing it wrong?

**Comment by avital** [comment]
I'm not sure what you did but somehow this PR has a single commit co-authored by you and @mohitreddy1996. At this point I don't know what to propose other than to entirely reconstruct your branch and force push. You probably used rebase in some unexpected way during your development.

**Comment by mohitreddy1996** [comment]
I see few changes from here: #298 

As @avital mentioned, could be a rebase mishap.

**Pull request closed without merging**
