### PR TITLE
Reorg docs left pane, rename "patterns" to HOWTOs

### PR DESCRIPTION
**Pull request by avital**
This makes the HOWTO guides appear directly on the left navbar
on readthedocs.org, which should help with discoverability.

Going forward, I'd like to port all of our old HOWTOs over.
I have an example for how I'd like to do this here: #771

### CODE REVIEW

**Comment by 8bitmp3** [comment]
@avital Awesome idea.

I discovered Flax Basics by chance (under Guided Tour) after randomly clicking 2+ times — do you think it'd be better for discoverability if (some of) the nested topics are automatically collapsed/visible? Or the Flax Basics notebook becomes the Flax Quickstart — an "independent" topic somewhere at the top the main nav tree? LMKWYT, it's just a thought.

**Comment by avital** [comment]
Thanks @8bitmp3 -- that's very helpful feedback! I'll play around with making more things directly visible.

Please let us know about other feedback learning about Flax (ideally in a new discussion thread) -- we're too deep into it to notice the challenges for people joining the community. We would like to smooth out the onboarding process.

**Comment by avital** [comment]
@8bitmp3 -- I committed https://github.com/google/flax/pull/778/commits/7a447b1c052da87c3dc1cc0798f17adcac9dae5f which makes the left navbar look like this now. WDYT?

Screenshot 2020-12-29 at 22 18 33

**Review by 8bitmp3 — COMMENTED** [review]
@avital Dit is geweldig! 🙂 (...I used Google Translate)

**Comment by avital** [comment]
Bedankt @8bitmp3 :)

**Review by levskaya — APPROVED** [review]
Looks good!

**Pull request merged**
