### PR TITLE
Add more meaningful error message to batchnorm

### PR DESCRIPTION
**Pull request by ayush-1506**
Fixes: #214 

Replaced the error message with a more specific message as mentioned in the issue thread. Kindly let me know if it's better to have some other message here.

### CODE REVIEW

**Comment by danielsuo** [comment]
As @avital mentioned in #214, this is a good opportunity to rethink the error message (understanding that the API for stateful contexts may change).

What would help guide you to doing the right thing? Perhaps a link to the `state` documentation in the guided tour ([link](https://flax.readthedocs.io/en/latest/notebooks/flax_guided_tour.html#State
))? Maybe flesh out the `BatchNorm` documentation more with an example and link to it as well?

**Comment by ayush-1506** [comment]
@danielsuo Thanks for the input. I could add an example of BatchNorm usage in the batchnorm docstring and link that in the error message (along with adding the link to flax). Would that be better?

**Comment by ayush-1506** [comment]
ping @danielsuo @avital

**Comment by danielsuo** [comment]
I think that would be a reasonable start, but this might need @avital's attention since he may have an opinion. I could imagine more of our error messages using this one as a template.

**Comment by ayush-1506** [comment]
Ok, I guess I'll probably wait for @avital 's input here.

**Comment by AlexeyG** [comment]
The proposed error message is strictly better than the current behaviour. Moving forward, once the FLIPs land, error messages like that would no longer be possible.

**Pull request merged**
