### PR TITLE
move DCGAN community example from deprecated to Linen

### PR DESCRIPTION
**Pull request by bkkaggle**
I said i'd update this a while ago but school unfortunately got in the way :) 
Screen Shot 2020-12-17 at 12 56 31 PM

Here's the updated [notebook](https://github.com/bkkaggle/jax-dcgan/blob/main/dcgan.ipynb)

### CODE REVIEW

**Comment by andsteing** [comment]
Thanks for updating this!

**Comment by bkkaggle** [comment]
Hi thanks for merging this in :), I just checked the [docs](https://flax.readthedocs.io/en/latest/examples.html#using-linen) and it looks like I left in an extra space at the beginning of the table row that breaks the table formatting. I pushed up the correct version to my [fork](https://github.com/bkkaggle/flax/commit/defef4cddc09f8a52f5e0ddc233c0af29fde2a79) that should fix this

**Comment by andsteing** [comment]
I think you'll need to open another PR in that case.

**Comment by bkkaggle** [comment]
yep will do that rn

**Pull request merged**
