### PR TITLE
Add Gaussian process regression example

### PR DESCRIPTION
**Pull request by danieljtait**
3 basic examples with increasing complexity centered around Gaussian processes regression models primarily aimed at demonstrating returning "distribution-like" objects from module layers using the nn.struct.dataclass decorator

### CODE REVIEW

**Comment by AlexeyG** [comment]
Hi @danieljtait , thanks for the PR! This looks very comprehensive, and it's great to see Flax being used for new models!

It would great to have a mini-example of a Gaussian Process in `flax/examples`. Doing this however will come with some maintenance expectations on the author of the example. We're still figuring this out, but it will at least include tests, expected metrics, being self-contained (e.g. see `examples/lm1b`) and ownership and commitment to updating the example with changing APIs and patterns. If you would like to work such an example, please let us know.

In the meantime, if you upload your example in a different GitHub repo, we would be happy to link to it!

**Comment by danieljtait** [comment]
Hi @AlexeyG thanks for the response! Would be delighted to take on the work of keeping a Gaussian process example updated and maintained through changes in the API and modelling patterns in Flax 

In the meantime I will checkout the example you pointed me to and then upload this example to a different repo and pass on the link to you guys. Loving `Flax`, keep up the good work!

**Comment by avital** [comment]
Hi @danieljtait -- we're almost ready to start taking in new meaningful examples but we need to finish setting up our end-to-end performance regression testing infrastructure.

In the meanwhile, we really want to link to your repo -- is it available somewhere?

**Comment by danieljtait** [comment]
Hi @avital -- great I would love to contribute when you're ready! 

In the meantime I have packaged up these examples at https://github.com/danieljtait/ladax/tree/master/examples and a link would be fantastic

**Comment by avital** [comment]
Hi @danieljtait! We added a link to your repository at https://github.com/google/flax/blob/master/examples/README.md. Thanks a lot, and please do let know if you have other questions or if you've implemented other great models with Flax!

**Pull request closed without merging**
